on: [push]

jobs:
  checkly_mac:
    runs-on: ubuntu-latest
    name: Checkly Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Private Action
        uses: ./
        id: checkly
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
        with:
          path: ./myCheck.yml
      - name: Test Result
        run: echo "Result - ${{ steps.checkly.outputs.result }}"
