on: [push]

jobs:
  checkly_mac:
    runs-on: ubuntu-latest
    name: Checkly Check
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkly Check Parser
        uses: ./
        id: checkly
        env:
          CHECKLY_API_KEY: ${{ secrets.CHECKLY_API_KEY }}
          REDIS_HOST: ${{ secrets.REDIS_HOST }}
          REDIS_PORT: ${{ secrets.REDIS_PORT }}
          REDIS_PW: ${{ secrets.REDIS_PW }}
        with:
          path: ./myCheck.yml
